### ISSUE TITLE
Import telegraf in nestjs app

### ISSUE THREAD

**Issue by 3dmagicus** [telegraf/telegraf#1411]
Hi all. I`m created a simple module (telegram-bot) in nestjs app.
Here is a simple service importing telegraf - telegram-bot.service.ts:

```
import { Injectable, OnApplicationBootstrap } from '@nestjs/common';
import { Telegraf } from 'telegraf';
import config from 'config';

interface TelegramConfig {
  token: string
}

const TELEGRAM_CONFIG: TelegramConfig = config.get('telegram');

@Injectable()
export class TelegramBotService implements OnApplicationBootstrap {
  private bot: Telegraf;

  onApplicationBootstrap(): void {
    const { token } = TELEGRAM_CONFIG;
    this.bot = new Telegraf(token);
    this.bot.start((ctx) => ctx.reply('Hello'));
    this.bot.launch();
  }
}
```
But compilation errors appear in console:

```
node_modules/telegraf/typings/composer.d.ts:30:25 - error TS1005: ']' expected.

30     [P in tt.UpdateType as SnakeToCamelCase<P>]: PropOr<U, P, undefined>;
                           ~~

node_modules/telegraf/typings/composer.d.ts:30:28 - error TS1005: ';' expected.

30     [P in tt.UpdateType as SnakeToCamelCase<P>]: PropOr<U, P, undefined>;
                              ~~~~~~~~~~~~~~~~

node_modules/telegraf/typings/composer.d.ts:30:47 - error TS1005: '(' expected.

30     [P in tt.UpdateType as SnakeToCamelCase<P>]: PropOr<U, P, undefined>;
                                                 ~

node_modules/telegraf/typings/composer.d.ts:30:48 - error TS1135: Argument expression expected.

30     [P in tt.UpdateType as SnakeToCamelCase<P>]: PropOr<U, P, undefined>;
                                                  ~

node_modules/telegraf/typings/composer.d.ts:30:73 - error TS1005: '(' expected.

30     [P in tt.UpdateType as SnakeToCamelCase<P>]: PropOr<U, P, undefined>;
                                                                           ~
....
```
What are the solutions?

**Comment by 3dmagicus** [comment]
I`m sorry.  The problem was with the typescript version. I had version 4.0.5 in my project, when I updated to 4.2.3 everything compiled without errors.

**Comment by isbabaev** [comment]
@3dmagicus Thank you! I had same issue
